name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 7.0.100

    - name: Build and Publish
      run: |
        dotnet publish -c Release -r win-x64
        echo "::set-output name=publish-dir::$(pwd)/bin/Release/net7.0-windows/win-x64"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WinFormsApp
        path: ${{ needs.build.outputs.publish-dir }}

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: WinFormsApp

    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Artifact to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WinFormsApp.zip
        asset_name: WinFormsApp.zip
        asset_content_type: application/zip

    - name: Update Auto-Update Endpoint
      run: |
        echo "::set-output name=auto-update-url::https://github.com/${{ github.repository }}/releases/download/v${{ github.run_number }}/WinFormsApp.zip"

    - name: Update Auto-Update Configuration
      run: |
        echo "auto-update-url=${{ steps.update_auto_update.outputs.auto-update-url }}" > auto-update.config

    - name: Commit and Push Auto-Update Configuration
      run: |
        git add auto-update.config
        git commit -m "Update auto-update configuration"
        git push
