name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
      
    - name: Build
      run: |
        cd SIGL_Cadastru 
        dotnet build --configuration Release
        xcopy Resources publish\Resources /E /I

    - name: dotnet publish
      if: github.event_name != 'pull_request'
      run: | 
        cd SIGL_Cadastru 
        dotnet publish --configuration Release -o ./publish

    - name: Clowd.Squirrel
      if: github.event_name != 'pull_request'
      run: |
        cd SIGL_Cadastru 
        Set-Alias Squirrel ($env:USERPROFILE + "\.nuget\packages\clowd.squirrel\2.11.1\tools\Squirrel.exe");
        Squirrel pack --framework net7,vcredist143-x86 --packId "SIGL_Cadastru" --packVersion "${{github.ref_name}}" --packAuthors "Balan Veniamin" --packDir .\publish\ --releaseDir .\Release\

    - name: Upload artifact for deployment job
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: ./Release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          D:/a/SIGL_Cadastru/SIGL_Cadastru/SIGL_Cadastru/Release/RELEASES
          D:/a/SIGL_Cadastru/SIGL_Cadastru/SIGL_Cadastru/Release/SIGL_Cadastru-${{github.ref_name}}-full.nupkg
          D:/a/SIGL_Cadastru/SIGL_Cadastru/SIGL_Cadastru/Release/SIGL_CadastruSetup.exe